### ISSUE TITLE
Extension popup window appears smaller in Vivaldi browser

### ISSUE THREAD

**Issue by mtaki14** [QOAL/localisetime#25]
This is probably some issue with the browser itself but I wonder if something could be changed on the extension's side since other extension popups appear fine. I'm creating this issue in the hope that it might be an easy fix/change.

See attached screenshot. The popup appears much smaller than it should, resulting in a lot of information being cut off

![image](https://github.com/QOAL/localisetime/assets/7987430/b94f635c-2c47-4264-91d8-9b960cceedcb)

**Comment by QOAL** [comment]
Hi, thank you for taking the time to report this.  
It's a weird little bug, that I don't quite understand, and haven't seen before.

I've fixed it, and I've submitted 1.30.4 to the Chrome Web Store.
(I won't bother with a Firefox release as it seems unaffected)

**Comment by mtaki14** [comment]
Thanks for the quick response. But unfortunately I still experience the same issue in the latest version.

**Comment by mtaki14** [comment]
There's probably some regression in Vivaldi itself though. In the stable build it works fine. In the snapshot/beta release it exhibits the behaviour decribed in the original post. Hopefully I can find more examples of extensions where this happens and get them to look into it. All other extensions I have installed seem to work fine though. Not sure what's different in this one in regards to how the popup is rendered.

**Comment by QOAL** [comment]
Ah. I've installed the latest snapshot and I can confirm that.   
I can mitigate the issue if I set a minimum width on the popup's body.
1.30.5, with this minor change, has been uploaded to the Chrome Web Store.
